apiVersion: v1
name: origin-ca-issuer
version: 0.6.0
appVersion: 0.6.1
description: A Helm chart for origin-ca-issuer
home: https://github.com/cloudflare/origin-ca-issuer
keywords:
  - cert-manager
  - cloudflare
  - tls
sources:
  - https://github.com/cloudflare/origin-ca-issuer
